### PR TITLE
Add a docker container to show import errors with mjoindicies.omi

### PR DESCRIPTION
**Pull request by markbasham**
Hi,

Juts trying to get things to build nicely, and i keep hitting some errors whether i use the pip install or the repo directly.

I thought the easiest thing to do was to create a docker container to try to run the tests as shown in the readme, and then possibly add the notebooks into it for playing with the data, and making sure the python env was set up as expected.

This is where I have got to so far, in the the docker container builds on dockerhub but has the specified import errors (which was what I found on my local machine too)

you can see the build [here](https://hub.docker.com/repository/registry-1.docker.io/markbasham/mjoindecies/builds/0b37ce04-5550-4ff8-8271-aab0b3380377) but you will need an account to see the result, so here are the errors on the test collection.

```
============================= test session starts ==============================

platform linux -- Python 3.7.6, pytest-5.4.3, py-1.8.2, pluggy-0.13.1
rootdir: /tests, inifile: pytest.ini
collected 40 items / 3 errors / 37 selected
==================================== ERRORS ====================================
___________________ ERROR collecting test_omi_calculator.py ____________________
ImportError while importing test module '/tests/test_omi_calculator.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_omi_calculator.py:32: in <module>
import mjoindices.omi.omi_calculator as omi
E ModuleNotFoundError: No module named 'mjoindices.omi'
________________ ERROR collecting test_quick_temporal_filter.py ________________
ImportError while importing test module '/tests/test_quick_temporal_filter.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_quick_temporal_filter.py:29: in <module>
import mjoindices.omi.quick_temporal_filter as qfilter
E ModuleNotFoundError: No module named 'mjoindices.omi'
_____________ ERROR collecting test_wheeler_kiladis_mjo_filter.py ______________
ImportError while importing test module '/tests/test_wheeler_kiladis_mjo_filter.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_wheeler_kiladis_mjo_filter.py:30: in <module>
import mjoindices.omi.wheeler_kiladis_mjo_filter as wkfilter
E ModuleNotFoundError: No module named 'mjoindices.omi'
=========================== short test summary info ============================
ERROR test_omi_calculator.py
ERROR test_quick_temporal_filter.py
ERROR test_wheeler_kiladis_mjo_filter.py
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 3 errors in 5.46s ===============================
```

Cheers

Mark

### CODE REVIEW

**Comment by markbasham** [comment]
Sorry looking at the error messages again, and it was a missing __init__.py file, which i have included and it looks like most of the tests now work fine.

**Comment by markbasham** [comment]
Hi @cghoffmann 

I'll leave this here, there are basically 2 changes in here which you would actually need to make to make the code work, the addition of an __init__.py file and the update of the trim() function as this has changed in recent versions of numpy , i.e. add axis=None to the arguments.  

The addition of a docker container may be of use, so feel free to use it if you like, and with the setup here it is easy to add it to be automatically built by dockerhub.

if you wish to test this you can run 

`docker run -p 8890:8890 markbasham/mjoindecies`

this will download the container and get it running, and then on a webpage on your local machine go to the page displayed at the end of the container output, it should be something like this:

`http://127.0.0.1:8890/?token=c1cfa736969f24330cb10e3e43ed6078d91d7066662c19ad'

Which will then open up the notepad ready to go.

There is still an issue for me with getting this runing, but it seems like a path issue on some saving, and all the code seens to run correctly, so hopefully its simple to sort out.

Cheers

Mark

**Comment by cghoffmann** [comment]
Hi @markbasham ,

Thank you very much for pointing us to these issues and particularly for directly working on the solutions! I will integrate your changes and work on the remaining path issue, which I can reproduce using your docker script.

To be honest, I was a bit surprised to see these issues popping up, since they never appeared to us on different systems. I guess that it has to do with the conda environment. We have indeed not extensively tested using conda and it seems that conda is more sensitive to these shortcomings or behaves somewhat differently (in the context of the remaining path problem).

I will immediately integrate your changes and then work on the remaining problem soon.

Thanks a lot,
Christoph.

P.S.: Sorry for the late reply, I was not in the office for a few weeks.

**Comment by cghoffmann** [comment]
Hi @markbasham,

I committed some minor changes (with major effects).

In setup.py file the option zip_safe=False was missing, so that the egg file was not unpacked and an internal reference data file could not be loaded. This caused the path issues, which you probably observed. Apparently, this did not have any effect in the environments, which we tested so far.

I also realized that one plotting routine does not work in the docker container due to internal problems, albeit working locally also in a conda environment. It turned out that the docker environment fetches matplotlib 3.3.0rc instead of an official release. I don't know why this happens, but added an explicit installation of matplotlib into the Dockerfile as a workaround.

Although I am quite optimistic that the problems are solved, I still have to repeat the tests on different systems in the coming days before making a new release. Anyway, it might already be worth looking at it now...

Thanks again for your support,
Christoph.

**Comment by markbasham** [comment]
Hi Christoph,

Thanks for the reply, sorry for not getting back sooner.  Glad the PR helped you spot some issues if nothing else :)

Good luck with the software in the future.

Cheers

Mark

**Comment by cghoffmann** [comment]
Hi Mark,

as you may have seen, I have made a new release from these changes, which is also archived in Zenodo and uploaded to PyPI.

Thanks again for your support,
Christoph.

**Comment by markbasham** [comment]
Hi Christoph,

Thats great news, Thanks for letting me know.

Cheers

Mark
________________________________

**Pull request merged**
